### ISSUE TITLE
Support Visual Studio 2017

### ISSUE THREAD

**Issue by cilerler** [martinjw/SmartPaster2013#2]
Please update the extension to support Visual Studio 2017

**Comment by martinjw** [comment]
We're looking into it ... !

**Comment by martinjw** [comment]
For my reference: http://www.visualstudioextensibility.com/2017/01/10/its-time-to-change-the-vsix-manifest-of-your-extension-to-v3-for-visual-studio-2017-compatibility/

**Comment by martinjw** [comment]
VS2017 pre-release here: https://github.com/martinjw/SmartPaster2013/releases/tag/v1.3

So far so good... If it's stable, I will publish this to the Visual Studio Gallery, certainly before the VS2017 RTM in March.

**Comment by martinjw** [comment]
Updated the Visual Studio Gallery
