### ISSUE TITLE
Feature request - Paste as escaped string

### ISSUE THREAD

**Issue by felixhao28** [martinjw/SmartPaster2013#4]
Hi, when I am dealing with paths in Windows, I want the backslashes to be escaped. For example: `C:\path\file.ext` will become `"C:\\path\\file.ext"` when "Paste As... -> Escaped String". I know I can use `@String` in C# to avoid it but there is no such feature in C++.

**Comment by martinjw** [comment]
The "Paste As Literal String" option escapes all the backslashes

**Comment by felixhao28** [comment]
![vs17pasteas](https://user-images.githubusercontent.com/2417391/29310142-36243648-81df-11e7-88c9-df6d93481ac8.gif)

**Comment by martinjw** [comment]
Fix coming

**Comment by felixhao28** [comment]
Ok, so it's bug. That makes sense. FYI, I am using VS 2017 preview on Win 10.

**Comment by martinjw** [comment]
Release https://github.com/martinjw/SmartPaster2013/releases/tag/1.4.1 
I will publish Saturday if nothing comes up in testing
